# Redirect to MudPi Assistant when no other site is configured
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  root /var/www/html/mudpi_assistant/app;
  index index.php index.html index.htm;

  server_name _ mudpi.local;

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/php-fpm.sock;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
  }

  error_page 404 = @notfound;

  location @notfound {
    return 302 $scheme://mudpi.local;
  }
}
