[program:mudpi]
directory=/home/mudpi
user=mudpi
environment=PYTHONPATH='/home/mudpi/venv/lib',PATH='/home/mudpi/venv/bin:%(ENV_PATH)s'
command=/home/mudpi/venv/bin/mudpi -c /home/mudpi/core/mudpi/mudpi.config
autostart=true
autorestart=true
startretries=3
stderr_logfile=/home/mudpi/logs/error.log
stdout_logfile=/home/mudpi/logs/output.log
stopsignal=INT
stopwaitsecs=180
